### ISSUE TITLE
Clicking Anywhere Closes Nav

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/content-demo-navigation#12]
Rather then having to click directly on the icon to close the navigation. When a user touches anywhere on the screen the navigation will close.

**Comment by mmeiers** [comment]
@ryanpet 
I noticed you made this change. Thanks, It works!

I realize this was a small change but in the future could you not make change until I assign the enhancement or bug to you? I may add more stuff in here that doesn't need to be done right away.

Also can you make sure and make comments in here rather than email when you complete something? There are other people that want to track what is going on with this repo.

**Comment by ryanpet** [comment]
ok.
