### ISSUE TITLE
Touch presentations do not work

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/content-demo-navigation#24]
Touch presentations do not work due to adding the touch anywhere to close navigation change.
Please make changes to gh-pages branch.
http://www.screencast.com/t/PAy8mOfvSI

**Comment by ryanpet** [comment]
i removed transparent-box that covered the iframe content.
clicking anywhere closes nav won't work anymore except on menu area.

**Comment by mmeiers** [comment]
Ok thanks I think well have to live without the touch anywhere for now.

**Comment by ryanpet** [comment]
ok.
