### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/content-demo-navigation#27]
Ryan,

Im noticing some performance issues with the demo navigation with the more templates we add to it. 
Css Animations are not smooth, gradients and small images render slowly ect.

(note: it works smoothly on my mac in chrome but we are trying to run this on a chrome box hooked up to a 4k monitor)

The navigation is assigning a value of display: none and opacity:0 so all webpages are constantly running just not all visible. Correct?

Can this be changed so that they are unloaded and loaded when needed?

Any other ideas that could increase the performance? Dont do anything yet just want to get some thoughts from you and an estimate on time involved if there is something you think can be done.

Thanks,
Mat

**Comment by ryanpet** [comment]
maybe some of the templates load to slow.

opacity is just for fade transition that we added.

for unloaded and loaded, not sure about this. maybe this will affect the template performance specially if template takes time to load.

if it works fine on your mac, maybe chrome box speed affects the performance.

**Comment by ByronDarlison** [comment]
@ryanpet can you confirm for me if we every html page that we add to this app get's opened and is playing in the background while it isn't being shown?

@alex-deaconu can you follow this discussion I'm probably going to need some advice from you on this...

Thanks

**Comment by ryanpet** [comment]
@ByronDarlison yes. all iframe content were loaded but hidden when not active.

I send new copy to @mmeiers which I added some changes. All iframe content were removed when not active.

**Comment by ByronDarlison** [comment]
Thanks @ryanpet. @mmeiers let me know if you see any improvement with this version. Thanks

**Comment by mmeiers** [comment]
@ryanpet @ByronDarlison This did improve the performance significantly.
I have pushed live to production and tested.

**Comment by ByronDarlison** [comment]
Awesome. Thanks @ryanpet !
