### ISSUE TITLE
Navigation List Needs to be scrollable/swipeable

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/content-demo-navigation#31]
Per this document the navigation list should be scrollable.
https://docs.google.com/document/d/1TGHhbWL48d-KtNY7WMgh9fqmv6N-j4PIZFFmB-iZu2c/edit#

Once there are more items in the list then will fit on the current screen resolution it should become scrollable so a user can swipe with their finger to navigate. Right now the list just goes off the bottom of the page. 

http://www.screencast.com/t/D35lWXuiQ

I added more template items as a test to a branch called "staging_scroll-test".

You can modify this branch or start your own to make this change.
Let me know if you have any questions.

Thanks,
Mat

**Comment by ryanpet** [comment]
done.please check.

**Comment by mmeiers** [comment]
looks good thanks
