### ISSUE TITLE
White Flash between Presentations

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/content-demo-navigation#8]
When the chrome demo navigation transitions between two urls (templates) I see a very noticeable white flash with no fade in transitions.
This happens in our chrome demo app and packaged app player.

here is a recap:
http://www.screencast.com/t/fuqfsG4MjMb4

I don't notice it when I preview the navigation by itself outside of both of these environments.
http://commondatastorage.googleapis.com/risemedialibrary-395c64e5-2930-460b-881e-009aabb157df/content-demo-navigation/index.html

I have noticed it works fine on Chrome v 36.0.1985.143. But 90% of the our computers run 37 or later where it is in issue.

**Comment by mmeiers** [comment]
@ryanpet Looks like the white space is greatly reduced. Im going to keep bug open for now and monitor.

What was the fix?
Speeding up the transition or changing the layering and opacity of hidden template?
Or both?
Thanks

**Comment by ryanpet** [comment]
I've removed the hiddem item. You can also speed up the transition.
